### ISSUE TITLE
rem函数不多余吗？

### ISSUE THREAD

**Issue by ygtzz** [crossjs/postcss-flexible#4]
非desktop时候，大部分属性都转为rem，只有font-size才用dpr的px，默认设置转为rem不就行了。省的要写很多rem函数。

**Comment by vvenv** [comment]
rem 函数存在的价值是：
- 针对设计稿编写样式表时，可以直接写入给定的像素值，无需在脑海或计算器中计算一遍；

    比如，设计稿中给定的是 100px，在 remUnit 是 75 的情况下，

    如果设计稿给定某个元素的宽度值是 100px，我们要计算后写入`width: 1.333333rem`；我们直接使用 rem(75px)，省去了纠结的计算。 

- remUnit 是一个可以自定义的变量。

    当需要对页面内容进行缩放时（一般是文字的放大缩小），我们可以简单地通过修改 remUnit 来实现。

当然，这个函数不是必须的，只是作为一种可能的选择。

**Comment by ygtzz** [comment]
不是的，直接写100px，检测到直接转成rem单位不就行啦。
关键一点是，引入了第三方的css文件，里面全是px，还要在每处加上rem函数去转换，岂不太累？
加个全局的黑名单来控制不转的不就行了。

**Comment by vvenv** [comment]
不能直接转，因为一个样式文件内，会存在有些 px 需要转，有些 px 不需要转的情况；

对于这种情况，常见的解决方案是一个个地加标识（比如 px2rem 用的是注释），但是对于如下情况支持得不够好：

```css
background-position: 100px 50px; /* 可能的需求有：全转，全不转，只转某一个。注释不好写 */
```

所以，采用自定义的函数，虽然侵入性太强，但是支持的场景更全面，这是一种折衷。

对于第三方的 css 文件，因为实际工作中没有应用，所以没有太多的思考，后面有涉及会考虑支持，如果你有好的想法，欢迎提交 PR。

谢谢。

**Comment by ygtzz** [comment]
好的
